import Head from 'next/head'
import Header from '../components/Header/Header'
import Principal from '../components/Principal/Principal'
import WpButton from '../components/WpButton/WpButton'
import Empresas from '../components/empresas/empresas'
import Clientes from '../components/Clientes/Clientes'
import Nosotros from '../components/Nosotros/Nosotros'
import Modelos from '../components/Modelos/Modelos'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Store in house</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="home"></div>
        <Header/>
        <Principal/>
        <WpButton/>
        <h2 id="empresas">Empresas</h2>
        <Empresas/>
        <h2 id="clientes">Clientes</h2>
        <Clientes/>
        <h2 id="nosotros">Nosotros</h2>
        <Nosotros/>
        <h2 id="modelos">Modelos</h2>
        <Modelos/>
      </main>
      <Footer/>
    </>
  )
}
