import Head from 'next/head'
import Header from '../components/Header/Header'
import Principal from '../components/Principal/Principal'
import Empresas from '../components/empresas/empresas'
import Clientes from '../components/Clientes/Clientes'

export default function Home() {
  return (
    <>
      <Head>
        <title>Store in house</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Principal/>
        <h2 id="empresas">Empresas</h2>
        <div className="max-width">
          <Empresas/>
        </div>
        <div className="max-width">
          <h2 id="clientes">Clientes</h2>
          <Clientes/>
          <Principal/>
        </div>

      </main>
    </>
  )
}
