import Head from 'next/head'
import Empresas from '../components/empresas/empresas'
import Header from '../components/Header/Header'
import Principal from '../components/Principal/Principal'

export default function Home() {
  return (
    <>
      <Head>
        <title>Store in house</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Principal/>
        <h2>Empresas </h2>
        <Empresas/>
      </main>
    </>
  )
}
