import React, { useState } from "react"
import Image from "next/image"
import Head from "next/head"
import HeaderServicios from "../../components/HeaderEmpresa/HeaderServicios"
import Principal from "../../components/Principal/Principal"
import FooterGiovagnoli from "../../components/Footer/FooterGiovagnoli"
import {FaChevronRight,FaChevronLeft} from "react-icons/fa"

export default function Magnani(){
    const SliderData = [
        {
            image : "/giov/marca1.png"
        },
        {
            image : "/giov/marca2.png"
        }
        
    ]
    
    const [current,setCurrent] = useState(0);
    const lengthArray = SliderData.length
    
    const nextSlide = () =>{
        setCurrent(current === lengthArray-1 ? 0 : current +1);
    }
    
    const prevSlide = () =>{
        setCurrent(current === 0 ? lengthArray-1 : current-1);
    }
    
    if(!Array.isArray(SliderData) || lengthArray <=0 ){
        return null
    }
    return(
        <>        
            <Head>
                <title>Store in house | Giovagnoli</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderServicios/>
            <main>
                <Principal/>
                <h2 id="nosotrosEmpresa">Nosotros</h2>
                    <div className="colorFondo">    
                        <div className="imagenFondoNosotrosGiov">
                            <div className="containerTextoNosotros">
                                <p className="textoNosotrosGiov">
                                    <strong>Innovacion al servicio de la industria:</strong> <br/>Somos una empresa comprometida
                                    con la industria a través de la comercialización de productos y servicios. Contamos con más de 
                                    20.000 productos de stock, local comercial, taller de reparación de motores eléctricos, equipos 
                                    de lubricación y RepCenter.
                                    Dessarrollamos soluciones integrales para cada sector industrial, nuestro equipo de especialistas
                                    e ingenieros, estarán ahí para ayudarlos.
                                    Más de 50 años nos avalan acompañando a diversos segmentos industriales como alimentación, siderurgia,
                                    metalmecánica, minería, agroindustria, energía, entre otros.
                                </p>
                            </div>
                        </div>
                    </div>
                <h2 id="marcas">Principales marcas</h2>
                <div className="slider">
                    <FaChevronLeft className="left-arrow" onClick={prevSlide}/>
                    <FaChevronRight className="right-arrow" onClick={nextSlide}/>
                    {SliderData.map((slide,index)=>{
                        return ( 
                            <div className={index === current ? "slide-active" : "slide" } key={index}>
                                {index===current && (<Image src={slide.image} alt="imagen" width={2620} height={440} ></Image>)}
                            </div>
                        )
                    })} 
                </div>
                <h2 id="servicios">Servicios</h2>
                    <div className="displayImagenesSoluciones">
                        <div className="imagenSoluciones1Giov">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSolucionesGiov">
                                        Consultoría economía circular:
                                        Manten tus activos mas productivos, reduce tu huella de CO2.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones2Giov">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSolucionesGiov">
                                        Rebobinados motores eléctricos:
                                        Mantenimiento y bobinado de motores en baja tensión.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones3Giov">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSolucionesGiov">
                                        Servicios para activos:
                                        Alineaciones, balanceos, dashboard industria 4.0, asesoria.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones4Giov">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSolucionesGiov">
                                        Mantenimiento predictivo:
                                        Monitoreo de condiciones de activos on line/off line.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones5Giov">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSolucionesGiov">
                                        Capacitaciones:
                                        Transferimos nuestros conocimientos para ayudarte en tu operación.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                <h2 id="productos">Productos</h2>
                    <div className="displayImagenesProductos">
                        <div className="imagenProductos1Giov">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Cesped y jardín.
                                    </li>
                                    <li className="itemsProductos">
                                        Pinturería.
                                    </li>
                                    <li className="itemsProductos">
                                        Construcción.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos2Giov">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Herramientas eléctricas.
                                    </li>
                                    <li className="itemsProductos">
                                        Soldadura.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos3Giov">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Seguridad e higiene.
                                    </li>
                                    <li className="itemsProductos">
                                        Herramientas manuales.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos4Giov">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Hidráulica y neumática.
                                    </li>
                                    <li className="itemsProductos">
                                        Herrmientas de lubricación.
                                    </li>
                                    <li className="itemsProductos">
                                        Motores, generadores y compresores.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                <FooterGiovagnoli/>
            </main>
        </>
    )
}