import React, { useState } from "react"
import Image from "next/image"
import Head from "next/head"
import HeaderEmpresa from "../../components/HeaderEmpresa/HeaderEmpresa"
import Principal from "../../components/Principal/Principal"
import FooterMagnani from "../../components/Footer/FooterMagnani"
import {FaChevronRight,FaChevronLeft} from "react-icons/fa"

export default function Magnani(){
    const SliderData = [
        {
            image : "/mag/marca1.png"
        },
        {
            image : "/mag/marca2.png"
        },
        {
            image : "/mag/marca3.png"
        },
        {
            image : "/mag/marca4.png"
        },
        
    ]
    
    const [current,setCurrent] = useState(0);
    const lengthArray = SliderData.length
    
    const nextSlide = () =>{
        setCurrent(current === lengthArray-1 ? 0 : current +1);
    }
    
    const prevSlide = () =>{
        setCurrent(current === 0 ? lengthArray-1 : current-1);
    }
    
    if(!Array.isArray(SliderData) || lengthArray <=0 ){
        return null
    }
    return(
        <>        
            <Head>
                <title>Store in house | Magnani</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderEmpresa/>
            <main>
                <Principal/>
                <h2 id="nosotrosEmpresa">Nosotros</h2>
                    <div className="colorFondo">    
                        <div className="imagenFondoNosotros">
                            <div className="containerTextoNosotros">
                                <p className="textoNosotros">
                                    Somos una empresa con 50 años de trayectoria donde fusionamos visión, calidad, compromiso y pasión 
                                    por lo que hacemos. Orientamos nuestro trabajo hacia relaciones sólidas, cercanas y de largo plazo.
                                    La calidad humana de nuestra gente es el mayor capital que tenemos. Certificamos ISO 9001 de calidad,
                                    incorporando ISO 14001 para afianzar nuestro compromiso con el medio ambiente.
                                </p>
                            </div>
                        </div>
                    </div>
                <h2 id="marcas">Principales marcas</h2>
                <div className="slider">
                    <FaChevronLeft className="left-arrow" onClick={prevSlide}/>
                    <FaChevronRight className="right-arrow" onClick={nextSlide}/>
                    {SliderData.map((slide,index)=>{
                        return ( 
                            <div className={index === current ? "slide-active" : "slide" } key={index}>
                                {index===current && (<Image src={slide.image} alt="imagen" width={3450} height={498} ></Image>)}
                            </div>
                        )
                    })} 
                </div>
                <h2 id="soluciones">Soluciones</h2>
                    <div className="displayImagenesSoluciones">
                        <div className="imagenSoluciones1">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSoluciones">
                                        Analisís y estudios de calidad y puesta a tierra
                                    </li>
                                    <li className="itemsSoluciones">
                                        Proyectos y desarrollo de software de Gestión de Energía
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones2">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSoluciones">
                                        Desarrollo, diseño, implementación, instalación y puesta en marcha de Sistemas de 
                                        Energía Ininterrumpida.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones3">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSoluciones">
                                        Estudios y proyectos de Sistemas de Iluminación Profesional.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones4">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSoluciones">
                                        Energías Renovables.
                                    </li>
                                    <li className="itemsSoluciones">
                                        Ahorro y eficiencía Energética.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenSoluciones5">
                            <div className="containerTextoSoluciones">
                                <ul className="listSoluciones">
                                    <li className="itemsSoluciones">
                                        Automatización Industrial
                                    </li>
                                    <li className="itemsSoluciones">
                                        Realidad Aumentada.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                <h2 id="productos">Productos</h2>
                    <div className="displayImagenesProductos">
                        <div className="imagenProductos1">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Instrumentos de medición.
                                    </li>
                                    <li className="itemsProductos">
                                        Instalación Eléctrica.
                                    </li>
                                    <li className="itemsProductos">
                                        Automatización industrial.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos2">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Iluminación profesional.
                                    </li>
                                    <li className="itemsProductos">
                                        Climatización profesional.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos3">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Conductores eléctricos.
                                    </li>
                                    <li className="itemsProductos">
                                        Baja y media tensión.
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="imagenProductos4">
                            <div className="containerTextoProductos">
                                <ul className="listProductos">
                                    <li className="itemsProductos">
                                        Infraestructura y Datacenter.
                                    </li>
                                    <li className="itemsProductos">
                                        Tableros eléctricos
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                <FooterMagnani/>
            </main>
        </>
    )
}